language: node_js

node_js: stable

cache: npm

install:
  - npm ci

script:
  - npm run production

before-deploy:
  - rm public/.gitignore

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: public
  on:
    branch: master

notifications:
  email:
    on_success: never
    on_failure: always
